### ISSUE TITLE
OrganizationRole

### ISSUE THREAD

**Issue by jaygray0919** [gkellogg/rdf-distiller#10]
This structure correctly validates:

> {
> "@context": {
>      "@vocab": "http://schema.org/"
>    },
>    "@type": "Person",
>    "name": "Delia Derbyshire",
>    "sameAs": "http://en.wikipedia.org/wiki/Delia_Derbyshire",
>    "alumniOf": {
>      "@type": "OrganizationRole",
>      "alumniOf": {
>        "@type": "CollegeOrUniversity",
>        "name": "University of Cambridge",
>        "sameAs": "http://en.wikipedia.org/wiki/University_of_Cambridge"
>     },
>     "startDate": "1959"
>   }
> }

But when I select:
  

> Raw Output

Distiller throws this error:

>   XML Parsing Error: not well-formed
> Location: http://rdf.greggkellogg.net/distiller
> Line Number 5, Column 34:
> \<ns5:OrganizationRole http://www.w3.org/1999/02/22-rdf-syntax-ns#nodeID='b1'>
> ---------------------------------^

Source:
    https://schema.org/OrganizationRole

/jay

**Comment by gkellogg** [comment]
Sorry of the delayed reply. It may be that you didn't set the input type to "jsonld", and it tried to parse it did not detect the format, so used an HTML or XML parser. I get the following output:

@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix schema: <http://schema.org/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

```turtle
 [
     a schema:Person;
     schema:alumniOf [
       a schema:OrganizationRole;
       schema:alumniOf [
         a schema:CollegeOrUniversity;
         schema:name "University of Cambridge";
         schema:sameAs "http://en.wikipedia.org/wiki/University_of_Cambridge"
       ];
       schema:startDate "1959"
     ];
     schema:name "Delia Derbyshire";
     schema:sameAs "http://en.wikipedia.org/wiki/Delia_Derbyshire"
 ] .
```
