### ISSUE TITLE
NoMethodError when trying to transform

### ISSUE THREAD

**Issue by csarven** [gkellogg/rdf-distiller#12]
Unable to transform https://dokie.li/ . When I select RDFa->JSON-LD and raw:

http://rdf.greggkellogg.net/distiller?command=serialize&format=rdfa&output_format=jsonld&url=https:%2F%2Fdokie.li%2F&raw

There is a NoMethodError: undefined method `end_with?' for nil:NilClass

Did I miss an option somewhere? I've tried different formats but no go. RDFa is well-formed and valid as far as I can tell.

I get the same issue with other URLs eg http://csarven.ca/dokieli-rww

**Comment by gkellogg** [comment]
Fixed in 14f6b487181e8da442d18306f4ab43a54c86d5c5.
