### ISSUE TITLE
JSON-LD parser differences from JSON-LD Playground

### ISSUE THREAD

**Issue by markwilkinson** [gkellogg/rdf-distiller#19]
Hi Greg,

Not sure where the problem is, here.  It maybe with the RDF::Writer?  I checked on the Distiller page to make sure that it behaved the same as my code.  Here's the problem:

this JSON-LD:
 `{
  "@context": "https://rawcdn.githack.com/ResearchObject/ro-crate/8c85e590155d0e81d47786628838ab25a1035359/docs/1.1-DRAFT/context.jsonld",
  "@graph": [
    {
      "@id": "ro-crate-metadata.jsonld",
      "@type": "CreativeWork",
      "about": {
        "@id": "./"
      }
    },
    {
      "@id": "ro-crate-preview.html",
      "@type": "CreativeWork",
      "about": {
        "@id": "./"
      }
    },
    {
      "@id": "./",
      "@type": "Dataset",
      "name": [
        "Situación de COVID-19 en España"
      ],
      "publisher": {
        "@id": "https://ror.org/00ca2c886"
      },
      "creator": [
        {
          "@id": "https://ror.org/00ca2c886"
        }
      ],
      "url": [
        "https://covid19.isciii.es/resources/serie_historica_acumulados.csv"
      ]
    }
   ] 
}`

uses relative paths as its identifiers.  the @context does not have a @base (which is good, because the content of these files will move around).  However, when I read/write from JSON-LD to Turtle (RDF::Turtle::Writer) it doesn't write anything.  Putting the same JSON-LD into the https://json-ld.org/playground/ yields valid RDF, by assuming the base is the local base URI and all relative IDs become relative to that.  I have attempted to set base_uri: in the Writer, but it didn't seem to make a difference.

I've run out of troubleshooting ideas.  Can you suggest a path forward?

Cheers!

**Comment by gkellogg** [comment]
Normally, it would take the base from the location of the document, but if you use the form field, there is no base. The playground uses the location of the playground itself as the base, in this case. 

The Ruby API (and JSON-LD API) have a `base` option to override this. Without a base, relative IRIs can’t be made absolute, so they get dropped when creating RDF, which requires absolute IRIs.

You can try this using the [distiller](http://rdf.greggkellogg.net/distiller) and use the `base` option to give it some arbitrary location.

**Comment by gkellogg** [comment]
Try it using [this link](http://rdf.greggkellogg.net/distiller?command=serialize&format=jsonld&output_format=turtle&url=http:%2F%2Fexample.org%2F), that set's the Document URL to `http://example.org/` and outputs the following Turtle:

```ttl
@base <http://example.org/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix schema: <http://schema.org/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<> a schema:Dataset;
  schema:creator <https://ror.org/00ca2c886>;
  schema:name "Situación de COVID-19 en España";
  schema:publisher <https://ror.org/00ca2c886>;
  schema:url "https://covid19.isciii.es/resources/serie_historica_acumulados.csv" .

<ro-crate-metadata.jsonld> a schema:CreativeWork;
  schema:about <> .

<ro-crate-preview.html> a schema:CreativeWork;
  schema:about <> .
```

**Comment by markwilkinson** [comment]
Indeed that works!  (good to know the other functionality of that little box!)

What is the equivalent of "filling that box" in RDF.rb?  I am not able to find a way to write-out that JSON as Turtle from code...

**Comment by gkellogg** [comment]
All RDF readers and writers accept a `base_uri` option. For JSON-LD, it is aliased as the `base` option.

In the distiller, the document URL field does double service, to either load the document, or set `base_uri`,

**Comment by markwilkinson** [comment]
ah!  I had to put it on both ends - the reader and the writer.  I had only tried it on the write-end.  '

Now I'm golden!  Cheers!
