### ISSUE TITLE
Internal server error on invalid input (circular itemrefs)

### ISSUE THREAD

**Issue by Janpot** [gkellogg/rdf-distiller#6]
```
<div itemscope>
  <div id="ref">
    <div itemprop="name">friend1</div>
    <div itemprop="friend" itemscope>
      <div itemprop="name">friend2</div>
      <div itemprop="friend" itemscope itemref="ref"></div>
    </div>
  </div>
</div>
```

This is invalid but crashes the server

**Comment by gkellogg** [comment]
I updated it to version 1.1.9, which includes a fix to the Microdata processor to look for such recursion. Thanks! Turn on validation to see the error.

(Also added as a negative syntax test to the Microdata to RDF test suite).

**Comment by Janpot** [comment]
I might be wrong but it seems like the ['microdata to rdf' algorithm](http://www.w3.org/TR/microdata-rdf/#h3_rdf-conversion-algorithm) doesn't check for circular structures while the ['microdata to json' algorithm](http://www.w3.org/TR/microdata/#json) does. The [microdata spec](http://www.w3.org/TR/microdata/#associating-names-with-items) prohibits circular structures though.

**Comment by gkellogg** [comment]
Microdata to RDF mostly defers to the Microdata spec for processing, and it does have such checks. However, these are now in the JSON processing steps, so some amount of developer license is necessary. A formal spec would likely need to add clarity. A test will help ensure that known pathological cases are detected.

**Comment by gkellogg** [comment]
We should have a wiki on the w3c Microdata-RDF repo to catalog implementations, and perhaps, collect implementation reports.
