### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by Janpot** [gkellogg/rdf-distiller#7]
On following url:
http://rdf.greggkellogg.net/distiller?format=jsonld&in_fmt=rdfa&uri=http://crefovi.com

**Comment by Janpot** [comment]
Another one:
http://rdf.greggkellogg.net/distiller?format=jsonld&in_fmt=rdfa&uri=http://gem-corporation.be

**Comment by gkellogg** [comment]
The current architecture has problems handling different exceptions, and they get rendered as server errors. I've been planing to refactor it, along the lines of changes I made to the Linter. This would make it a webApp which handled server requests using an Ajax request, and so would be more resilient to parser exceptions.

**Comment by Janpot** [comment]
Ok, I understand.
Do you want me to add more examples when I find them or do these suffice?

**Comment by gkellogg** [comment]
Unless they're really quite different things, they're all examples of the same underlying problem.

**Comment by gkellogg** [comment]
Fixed and deployed in 44de22bc5990fe85ac0172a1d53fc77429bade42
