### ISSUE TITLE
'incompatible character encodings' on some form input

### ISSUE THREAD

**Issue by Janpot** [gkellogg/rdf-distiller#8]
Trying to use the distiller with the form input method on the website http://www.burny-shop.de/. (view-source in chrome and copy+paste in the markup field). It always returns with

```
incompatible character encodings: ASCII-8BIT and UTF-8
```

I have this issue on a lot of sites and it was introduced in 1.1.11 o2 1.1.12. I didn't have this before. It seems to be the following line that makes this happen:

```
<a  href="?ObjectPath=/Shops/62542650/Categories/Zubeh%C3%B6r">Zubehör</a>
```

You can just copy+paste this line in the markup box to see the problem in action

**Comment by gkellogg** [comment]
I'm not sure what might have changed, but is probably needs to detect and convert input which is sent as form data. Do you also have the problem if you just use a URL?

I should be able to look into it later today.

**Comment by Janpot** [comment]
No, just the url works.

**Comment by gkellogg** [comment]
Issue in Ruby `URI.unescape`: http://stackoverflow.com/questions/10328086/uri-unescape-crashes-as-it-is-trying-to-convert-c39fą-to-ßą.

Solution seems to be to force binary before unescape, and then force back. Should also take anything non-UTF to UTF.

**Comment by Janpot** [comment]
This doesn't seem to work for me, the application crashes when I try to run it on this website's content.
Also it seems like http://rdf.greggkellogg.net/ is down now.

**Comment by gkellogg** [comment]
I updated gems and restarted, seems to be up now.

Your page may have some HTML errors which prevent proper parsing. I ran it through linter.structured-data.org and saw the following error message:

> Validation http://www.burny-shop.de/: Element script embeds close tag

Otherwise, please continue to update this issue and close when you're ready.

**Comment by Janpot** [comment]
I tried copy+pasting the source of http://www.burny-shop.de/ in the markup field and your website crashes.

**Comment by gkellogg** [comment]
It crashes if the input is too large and you set "Content Detect"; the thread ends up running too long. To get around this, set "Input Format" to "rdfa". "Content Detect" causes every reader to look at the data; Heroku then sends a SIGKILL to terminate the thread, which can't be caught.

I think the best thing to do is to disallow the use of "Content Detect" with form data, as it's really intended for doing content-negotiation based on the retrieved Content-Type header.

**Comment by Janpot** [comment]
Ok, good to know, My application is already calling it with input type 'rdfa'. Didn't realise it would cause this behaviour when I was testing this release manually. Will check next week how this behaves with the actual call I make and update the thread.

**Comment by Janpot** [comment]
@gkellogg Ok, having much better results now. Still seeing some weird errors with the form input. For instance the application seems to crash with 500 when I put in `%da` in the markup box.

**Comment by gkellogg** [comment]
The distiller was URI decoding the form input, which was also done lower in the stack. Thus, %da and %CA were URI decoded and were illegal as UTF-8. I've removed the double decode and will update shortly.

**Comment by gkellogg** [comment]
Updated in 1.1.15.

**Comment by Janpot** [comment]
@gkellogg Another thing I noticed is when script tags are used with `type="text/plan"`, the parser fails as well.

```
<script type="text/plain">text</script>
```

**Comment by gkellogg** [comment]
Since `text/plain` is an archaic type for N-Triples, it tries to parse this as N-Triples, and finds that it is invalid. So, this is expected behavior.

A future update to the rdf gem may remove `text/plain` as a content-type alias.

**Comment by Janpot** [comment]
Ok, as a solution I can remove those script tags from the html before sending it to your application. As well as the jsonld ones and parse those myself.
